defmodule Catena.ReproduciblePackageTest do
  use ExUnit.Case, async: false
  alias Catena.Package.Reproducible, as: R

  defp root do
    Path.join(System.tmp_dir!(), "catena-repro-#{System.unique_integer([:positive])}")
  end

  defp files do
    source = %{
      "version" => "0.1.6",
      "origin" => "pkg://repro/main",
      "module" => "ReproMain",
      "exports" => ["main"],
      "definitions" => [
        %{
          "name" => "main",
          "parameters" => [],
          "signature" => %{"forall" => [], "type" => %{"tag" => "integer"}},
          "body" => %{"tag" => "integer", "value" => 42}
        }
      ]
    }

    manifest = %{
      "format" => "catena-package-manifest",
      "version" => "0.1.6",
      "package" => "repro",
      "profile" => "static",
      "companion_module" => "ReproCompanion",
      "modules" => [
        %{
          "source" => "src/main.json",
          "beam" => "out/main.beam",
          "interface" => "out/main.cati.json"
        }
      ],
      "interfaces" => [],
      "roots" => [],
      "output" => "out/companion.beam",
      "assurance" => "out/assurance.json"
    }

    %{
      "package.json" => JSON.encode!(manifest),
      "src/main.json" => JSON.encode!(source),
      "catena.lock" => "exact-locked-content"
    }
  end

  test "independent clean roots produce identical full archives despite ambient environment" do
    previous =
      Map.new(["TZ", "ERL_COMPILER_OPTIONS", "CATENA_UNDECLARED"], &{&1, System.get_env(&1)})

    try do
      {:ok, plan} = R.plan(files(), "package.json")

      System.put_env(%{
        "TZ" => "UTC",
        "ERL_COMPILER_OPTIONS" => "[debug_info]",
        "CATENA_UNDECLARED" => "one"
      })

      a = root()
      assert {:ok, first} = R.build(plan, a)
      refute File.exists?(a)

      System.put_env(%{
        "TZ" => "Pacific/Auckland",
        "ERL_COMPILER_OPTIONS" => "[no_line_info]",
        "CATENA_UNDECLARED" => "two"
      })

      assert {:ok, second} = Catena.Package.Linker.compile_reproducible(plan, root())
      assert first == second
      assert map_size(first.outputs) == 4
      assert {:ok, decoded} = R.decode_archive(first.archive)
      assert decoded == first.outputs
      assert {:ok, assurance} = Catena.CanonicalJCS.decode(decoded["out/assurance.json"])
      assert assurance["signed"]["package"] == "repro"

      assert {:ok, {_, [compile_info: info]}} =
               :beam_lib.chunks(decoded["out/main.beam"], [:compile_info])

      refute inspect(info) =~ a
    after
      Enum.each(previous, fn {key, value} ->
        if value, do: System.put_env(key, value), else: System.delete_env(key)
      end)
    end
  end

  test "changed locked bytes toolchain and generator authority invalidate exact input identity" do
    f = files()
    {:ok, plan} = R.plan(f, "package.json")
    {:ok, changed} = R.plan(Map.put(f, "catena.lock", "replaced"), "package.json")
    refute changed["digest"] == plan["digest"]
    forged = put_in(plan["toolchain"]["compiler"], String.duplicate("0", 64))
    assert {:error, _} = R.verify(forged)
    assert {:error, _} = R.build(forged, root())

    assert {:error, _} =
             R.plan(f, "package.json",
               generators: [
                 %{"output" => "generated", "parts" => [%{"environment" => "UNDECLARED"}]}
               ]
             )

    assert {:error, _} = R.plan(f, "package.json", generators: [%{"shell" => "echo hidden"}])
  end

  test "declared deterministic generators bind public environment and generated byte identity" do
    f = files()
    source = f["src/main.json"]
    f = Map.delete(f, "src/main.json")
    generator = %{"output" => "src/main.json", "parts" => [%{"environment" => "SOURCE"}]}

    {:ok, plan} =
      R.plan(f, "package.json", environment: %{"SOURCE" => source}, generators: [generator])

    assert {:ok, _} = R.build(plan, root())
    changed_source = String.replace(source, "42", "43")

    {:ok, changed} =
      R.plan(f, "package.json",
        environment: %{"SOURCE" => changed_source},
        generators: [generator]
      )

    refute changed["digest"] == plan["digest"]
    refute changed["generated"] == plan["generated"]
    altered = put_in(plan["generators"], [])
    assert {:error, _} = R.verify(altered)
  end

  test "archive ordering metadata duplicates and tampering are checked" do
    input = String.duplicate("a", 64)
    assert {:ok, a} = R.archive(Map.new([{"b", "B"}, {"a", "A"}]), input)
    assert {:ok, ^a} = R.archive(Map.new([{"a", "A"}, {"b", "B"}]), input)
    {:ok, doc} = Catena.CanonicalJCS.decode(a)
    assert Enum.map(doc["files"], & &1["path"]) == ["a", "b"]
    assert Enum.all?(doc["files"], &(&1["mode"] == 420 and &1["mtime"] == 0))

    for entries <- [
          Enum.reverse(doc["files"]),
          doc["files"] ++ doc["files"],
          [Map.put(hd(doc["files"]), "mode", 493) | tl(doc["files"])]
        ] do
      assert {:error, _} =
               R.decode_archive(Catena.CanonicalJCS.encode(%{doc | "files" => entries}))
    end

    assert {:error, _} = R.archive(%{"../escape" => "bad"}, input)
    assert {:ok, empty} = R.archive(%{}, input)
    assert {:ok, %{}} = R.decode_archive(empty)
  end

  test "empty package still includes the companion and assurance while unsafe or overlapping paths fail" do
    f = files()
    manifest = JSON.decode!(f["package.json"])
    empty = %{manifest | "modules" => []}
    assert {:ok, plan} = R.plan(%{"package.json" => JSON.encode!(empty)}, "package.json")
    assert {:ok, %{outputs: outputs}} = R.build(plan, root())
    assert map_size(outputs) == 2

    for path <- ["../outside", "/absolute", "a/../b", "a\\b", "package.json"] do
      changed = Map.put(manifest, "output", path)

      assert {:error, _} =
               R.plan(Map.put(f, "package.json", JSON.encode!(changed)), "package.json")
    end

    occupied = root()
    File.mkdir!(occupied)
    File.write!(Path.join(occupied, "keep"), "user content")

    try do
      assert {:error, _} = R.build(plan, occupied)
      assert File.read!(Path.join(occupied, "keep")) == "user content"
    after
      File.rm_rf!(occupied)
    end
  end

  test "staging interruption and corruption preserve the previous archive until verified commit" do
    destination = root()
    {:ok, old} = R.archive(%{"old" => "bytes"}, String.duplicate("a", 64))
    {:ok, new} = R.archive(%{"new" => "bytes"}, String.duplicate("b", 64))
    File.write!(destination, old)

    try do
      {:ok, stage} = R.stage(new, destination)
      assert File.read!(destination) == old
      assert :ok = R.cancel(stage)
      assert File.read!(destination) == old
      {:ok, stage} = R.stage(new, destination)
      File.write!(stage.temporary, "interrupted partial write")
      assert {:error, _} = R.commit(stage)
      assert File.read!(destination) == old
      assert :ok = R.cancel(stage)
      {:ok, stage} = R.stage(new, destination)

      assert Task.async(fn -> R.commit(stage) end) |> Task.await() ==
               {:error, :archive_commit_failed}

      assert :ok = R.commit(stage)
      assert File.read!(destination) == new
    after
      File.rm(destination)
    end
  end

  test "full rebuild verification rejects a rehashed substituted output archive" do
    {:ok, plan} = R.plan(files(), "package.json")
    {:ok, built} = R.build(plan, root())
    assert :ok = Catena.Assurance.verify_reproducible(built.archive, plan, root())

    {:ok, forged} =
      R.archive(Map.put(built.outputs, "out/main.beam", "wrong bytes"), plan["digest"])

    assert {:ok, _} = R.decode_archive(forged)

    assert {:error, :reproducible_archive_mismatch} =
             Catena.Assurance.verify_reproducible(forged, plan, root())

    assert {:ok, key} = R.cache_key(plan)
    assert key == plan["digest"]
  end

  test "owner death between staging and publication never replaces the previous archive" do
    destination = root()
    File.write!(destination, "previous archive")
    {:ok, binary} = R.archive(%{"file" => "new"}, String.duplicate("a", 64))
    observer = self()

    owner =
      spawn(fn ->
        {:ok, stage} = R.stage(binary, destination)
        send(observer, {:staged, stage.temporary})

        receive do
          :never -> :ok
        end
      end)

    assert_receive {:staged, temporary}
    monitor = Process.monitor(owner)
    Process.exit(owner, :kill)
    assert_receive {:DOWN, ^monitor, :process, ^owner, :killed}
    assert File.read!(destination) == "previous archive"
    assert File.read!(temporary) == binary
    File.rm!(temporary)
    File.rm!(destination)
  end

  test "declared file generator and environment ceilings refuse whole inputs" do
    assert {:error, _} =
             R.plan(Map.put(files(), "large", :binary.copy(<<0>>, 16_777_217)), "package.json")

    crowded = Map.new(1..257, &{"file#{&1}", ""}) |> Map.merge(files())
    assert {:error, _} = R.plan(crowded, "package.json")
    assert {:error, _} = R.plan(files(), "package.json", environment: %{"bad-key" => "value"})

    assert {:error, _} =
             R.plan(files(), "package.json", environment: %{"VALUE" => :binary.copy("x", 65537)})

    assert {:error, _} = R.plan(files(), "package.json", generators: List.duplicate(%{}, 65))
    assert R.profile().cache == false
    assert R.profile().secret_dependent_builds == false
    assert Catena.ConformanceInfo.document()["reproducible_builds"]["version"] == "0.1.73"
  end

  test "sensitive provisioning inputs cannot enter a public reproducibility envelope" do
    {:ok, secret} = Catena.Runtime.Secret.input("synthetic-build-secret")
    assert {:error, _} = R.plan(Map.put(files(), "secret", secret), "package.json")
    assert {:error, _} = R.plan(files(), "package.json", environment: %{"TOKEN" => secret})
    assert {:error, _} = R.plan(files(), "package.json", hidden_option: true)
  end
end
