defmodule Catena.FileUnit do
  @moduledoc """
  The source-only Catena 0.1.16 file-unit resolver.

  One `.cat` file, its filename, and parser-supplied module-declaration
  events are resolved into one file unit — module or no-module, generated
  flag and tool identifier — or exactly one stable diagnostic. It does not
  parse declarations, tokenize source, resolve names, load code, or compile.
  """

  alias Catena.{Comment, Diagnostic, LanguageSelection, LanguageVersion, SourceSpan, SourceText}

  @file_unit_revision "0.1.16"
  @extension ".cat"
  @module_name ~r/^[A-Z][A-Za-z0-9_]*$/
  @marker_exact ~r/^ catena:generated by ([A-Za-z0-9_-]+)$/
  @marker_attempt ~r/^[\t ]*catena:generated/

  defmodule ModuleDeclaration do
    @moduledoc "One parser-supplied module-declaration event."

    @enforce_keys [:name, :span]
    defstruct @enforce_keys

    @type t :: %__MODULE__{name: String.t(), span: SourceSpan.t() | nil}
  end

  defmodule Result do
    @moduledoc "One resolved file unit with exact selection."

    @enforce_keys [:kind, :module, :generated, :tool, :selection]
    defstruct @enforce_keys

    @type t :: %__MODULE__{
            kind: :module | :no_module,
            module: %{name: String.t(), span: SourceSpan.t() | nil} | nil,
            generated: boolean(),
            tool: String.t() | nil,
            selection: LanguageSelection.t()
          }
  end

  @spec resolve(binary(), binary(), [ModuleDeclaration.t()], keyword()) ::
          {:ok, Result.t()} | {:error, Diagnostic.t()}
  def resolve(source, filename, module_declarations, options \\ [])
      when is_binary(source) and is_binary(filename) and is_list(module_declarations) and
             is_list(options) do
    with {:ok, selection} <- resolve_selection(Keyword.get(options, :language_selection)),
         :ok <- require_extension(filename),
         {:ok, decoded} <- SourceText.decode(source, language_selection: selection),
         {:ok, generated, tool} <- scan_marker(source, decoded) do
      resolve_declarations(filename, module_declarations, generated, tool, selection)
    end
  end

  defp resolve_selection(nil),
    do: require_file_unit_revision(LanguageVersion.legacy_selection(@file_unit_revision))

  defp resolve_selection(selection) do
    with {:ok, resolved} <- LanguageVersion.resolve_selection(selection) do
      require_file_unit_revision(resolved)
    end
  end

  defp require_file_unit_revision(
         %LanguageSelection{language_revision: @file_unit_revision} = selection
       ),
       do: {:ok, selection}

  defp require_file_unit_revision(%LanguageSelection{} = selection) do
    {:error,
     Diagnostic.new(
       "EDN001",
       "file-unit resolution requires language revision #{@file_unit_revision}",
       path: "$.language_revision",
       details: %{
         selected: selection.language_revision,
         required: @file_unit_revision,
         frontend: "files-and-modules"
       }
     )}
  end

  defp require_extension(filename) do
    if String.ends_with?(filename, @extension) do
      :ok
    else
      {:error,
       Diagnostic.new("FIL001", "a Catena source file must carry the .cat extension",
         details: %{reason: "missing_extension", filename: filename, expected: @extension}
       )}
    end
  end

  defp scan_marker(source, decoded) do
    units = List.to_tuple(decoded.units)
    size = tuple_size(units)
    index = first_significant(units, size, 0)

    cond do
      index >= size ->
        {:ok, false, nil}

      comment_opener?(units, size, index) ->
        with {:ok, comment} <- scan_comment(source, index) do
          classify_comment(comment)
        end

      true ->
        {:ok, false, nil}
    end
  end

  defp first_significant(_units, size, index) when index >= size, do: index

  defp first_significant(units, size, index) do
    if elem(units, index).scalar in [?\s, ?\t, ?\n] do
      first_significant(units, size, index + 1)
    else
      index
    end
  end

  defp comment_opener?(units, size, index) do
    scalar_at(units, size, index) == ?/ and scalar_at(units, size, index + 1) in [?/, ?*]
  end

  defp scalar_at(_units, size, index) when index >= size, do: nil
  defp scalar_at(units, _size, index), do: elem(units, index).scalar

  defp scan_comment(source, index) do
    case Comment.scan(source,
           unit_index: index,
           language_selection: LanguageVersion.legacy_selection("0.1.12")
         ) do
      {:ok, result} -> {:ok, result.comment}
      {:error, %Diagnostic{} = diagnostic} -> {:error, diagnostic}
    end
  end

  defp classify_comment(%Comment{kind: :ordinary, form: :line, body: body, span: span}) do
    cond do
      not Regex.match?(@marker_attempt, body) ->
        {:ok, false, nil}

      true ->
        case Regex.run(@marker_exact, body) do
          [_, tool] ->
            {:ok, true, tool}

          nil ->
            {:error,
             Diagnostic.new(
               "FIL005",
               "a first-unit generated marker comment fails the exact marker grammar",
               span: span,
               details: %{reason: "malformed_generated_marker"}
             )}
        end
    end
  end

  defp classify_comment(%Comment{}), do: {:ok, false, nil}

  defp resolve_declarations(filename, declarations, generated, tool, selection) do
    basename = basename_minus_extension(filename)

    cond do
      length(declarations) >= 2 ->
        {:error,
         Diagnostic.new("FIL002", "a file unit must not contain more than one module declaration",
           span: span_of(Enum.at(declarations, 1)),
           details: %{reason: "multiple_module_declarations", observed: length(declarations)}
         )}

      declarations == [] ->
        {:ok,
         %Result{
           kind: :no_module,
           module: nil,
           generated: generated,
           tool: tool,
           selection: selection
         }}

      true ->
        [%ModuleDeclaration{name: name, span: span}] = declarations

        if Regex.match?(@module_name, name) do
          if name == basename do
            {:ok,
             %Result{
               kind: :module,
               module: %{name: name, span: span},
               generated: generated,
               tool: tool,
               selection: selection
             }}
          else
            {:error,
             Diagnostic.new(
               "FIL004",
               "the declared module name does not equal the file basename minus extension",
               span: span,
               details: %{
                 reason: "basename_mismatch",
                 declared: name,
                 expected: basename
               }
             )}
          end
        else
          {:error,
           Diagnostic.new(
             "FIL003",
             "a file-level module name must be an ASCII uppercase-initial word",
             span: span,
             details: %{reason: "invalid_module_name_spelling", declared: name}
           )}
        end
    end
  end

  defp span_of(%ModuleDeclaration{span: span}), do: span

  defp basename_minus_extension(filename) do
    filename
    |> String.split(~r{[\\/]})
    |> List.last()
    |> String.slice(0..-(String.length(@extension) + 1)//1)
  end
end
